stages:
  - build
  - static_analysis
  - test
  - quality_gate
  - release

default:
  image: registry.smile.fr/formation-devsecops-embedded-iot/runner:2.3

build_job:
  stage: build
  script:
    - echo "=== Building the project ==="
    - # Add your build commands here
    - echo "=== End of Build Job ==="

static_analysis_job:
  stage: static_analysis
  script:
    - echo "=== Running static analysis ==="
    - # Add static analysis tools here
    - echo "=== End of Static Analysis Job ==="

test_job:
  stage: test
  script:
    - echo "=== Running unit tests ==="
    - # Add your unit testing commands here
    - echo "=== End of Unit Testing Job ==="

quality_gate_job:
  stage: quality_gate
  script:
    - echo "=== Running SonarScanner ==="
    - # Add SonarScanner configuration and commands here
    - echo "=== End of SonarScanner Job ==="

release_job:
  stage: release
  script:
    - echo "=== Releasing the application ==="
    - # Add your release commands here
    - echo "=== End of Release Job ==="
