stages:
  - build
  - static_analysis
  - test
  - quality_gate
  - release

default:
  image: registry.smile.fr/formation-devsecops-embedded-iot/runner:2.3

build:
  stage: build
  script:
    - echo "=== Building the project ==="
    - echo "=== End of Build Job ==="

static_analysis:
  stage: static_analysis
  script:
    - echo "=== Running static analysis ==="
    - echo "=== End of Static Analysis Job ==="

test:
  stage: test
  script:
    - echo "=== Running unit tests ==="
    - echo "=== End of Unit Testing Job ==="

quality_gate:
  stage: quality_gate
  script:
    - echo "=== Running SonarScanner ==="
    - echo "=== End of SonarScanner Job ==="

release:
  stage: release
  script:
    - echo "=== Releasing the application ==="
    - echo "=== End of Release Job ==="
